sudo: false

language: node_js

node_js:
  - "8.17"
  - "9.11"
  - "10.19"
  - "11.15"
  - "12.16"

install:
  - npm install yarn -g
  - npm install -g codecov
  - yarn install

cache:
  directories:
    - node_modules

script:
  - npm run test:coverage
  - codecov
