sudo: false

language: node_js

node_js:
  - "10.16"
  - "11.15"
  - "12.16"
  - "13.14"

install:
  - npm install yarn -g
  - npm install -g codecov
  - yarn install

cache:
  directories:
    - node_modules

script:
  - npm run test:coverage
  - codecov
